version: 2
jobs:
  lintJob:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run lint # run the `echo` command
  testJob:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install && npm test
  deployJob:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  any_build_name:
    jobs:
      - lintJob
      - testJob:
          requires:
            - lintJob
      - deployJob:
          requires:
            - testJob
